version: '3'
services:
  webapp:
    build:
      context: .
    environment:
      APP_NAME: 'First App'
      AWS_REGION: us-east-2
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      TABLE_NAME: DemoTable
    expose:
      - "8080"